# Generated by Django 6.0.1 on 2026-01-30 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Cuenta Bancaria'), ('tarjeta', 'Tarjeta de Crédito'), ('ahorro', 'Cuenta de Ahorro'), ('otro', 'Otro')], max_length=100)),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='accounts_name_94ecef_idx')],
            },
        ),
    ]
